#pragma once
enum ENUM_BUTTON_NUMBERS
{
    IDC_BUTTON_NUM_0 = 0, 
    IDC_BUTTON_NUM_1, IDC_BUTTON_NUM_2, IDC_BUTTON_NUM_3,
    IDC_BUTTON_NUM_4, IDC_BUTTON_NUM_5, IDC_BUTTON_NUM_6,
    IDC_BUTTON_NUM_7, IDC_BUTTON_NUM_8, IDC_BUTTON_NUM_9,
    IDC_BUTTON_NUM_A, IDC_BUTTON_NUM_B, IDC_BUTTON_NUM_C,
    IDC_BUTTON_NUM_D, IDC_BUTTON_NUM_E, IDC_BUTTON_NUM_F,
};

enum ENUM_OPERATOR
{
    IDC_BUTTON_PLUS = 32,
    IDC_BUTTON_MINUS,
    IDC_BUTTON_MULTIPLE,
    IDC_BUTTON_DIVIDE,
};

enum ENUM_CONVERtOR
{
    IDC_BUTTON_BINARY = 64,
    IDC_BUTTON_DECIMAL,
    IDC_BUTTON_HEXADECIMAL,
};

enum ENUM_ETC
{
    IDC_BUTTON_CLEAR = 128, 
    IDC_BUTTON_CLEAR_ALL,
    IDC_BUTTON_PAREN, 
    IDC_BUTTON_PAREN_LINE,
    IDC_BUTTON_UNARY,
    IDC_BUTTON_RUN
};


#define IDC_TEXTBOX (1200)